/* This file is auto-generated by TanStack Router and refreshed during build. */
import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as MapRouteImport } from "./routes/map";
import { Route as TripsRouteImport } from "./routes/trips";
import { Route as StopsRouteImport } from "./routes/stops";
import { Route as AlertsRouteImport } from "./routes/alerts";
import { Route as AssistantRouteImport } from "./routes/assistant";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as AdminRouteImport } from "./routes/admin";
import { Route as ApiChatRouteImport } from "./routes/api/chat";

const IndexRoute = IndexRouteImport.update({ id: "/", path: "/", getParentRoute: () => rootRouteImport } as any);
const MapRoute = MapRouteImport.update({ id: "/map", path: "/map", getParentRoute: () => rootRouteImport } as any);
const TripsRoute = TripsRouteImport.update({ id: "/trips", path: "/trips", getParentRoute: () => rootRouteImport } as any);
const StopsRoute = StopsRouteImport.update({ id: "/stops", path: "/stops", getParentRoute: () => rootRouteImport } as any);
const AlertsRoute = AlertsRouteImport.update({ id: "/alerts", path: "/alerts", getParentRoute: () => rootRouteImport } as any);
const AssistantRoute = AssistantRouteImport.update({ id: "/assistant", path: "/assistant", getParentRoute: () => rootRouteImport } as any);
const SettingsRoute = SettingsRouteImport.update({ id: "/settings", path: "/settings", getParentRoute: () => rootRouteImport } as any);
const AdminRoute = AdminRouteImport.update({ id: "/admin", path: "/admin", getParentRoute: () => rootRouteImport } as any);
const ApiChatRoute = ApiChatRouteImport.update({ id: "/api/chat", path: "/api/chat", getParentRoute: () => rootRouteImport } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute; "/map": typeof MapRoute; "/trips": typeof TripsRoute;
  "/stops": typeof StopsRoute; "/alerts": typeof AlertsRoute; "/assistant": typeof AssistantRoute;
  "/settings": typeof SettingsRoute; "/admin": typeof AdminRoute; "/api/chat": typeof ApiChatRoute;
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {
  __root__: typeof rootRouteImport; "/": typeof IndexRoute; "/map": typeof MapRoute;
  "/trips": typeof TripsRoute; "/stops": typeof StopsRoute; "/alerts": typeof AlertsRoute;
  "/assistant": typeof AssistantRoute; "/settings": typeof SettingsRoute; "/admin": typeof AdminRoute;
  "/api/chat": typeof ApiChatRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/map" | "/trips" | "/stops" | "/alerts" | "/assistant" | "/settings" | "/admin" | "/api/chat";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/map" | "/trips" | "/stops" | "/alerts" | "/assistant" | "/settings" | "/admin" | "/api/chat";
  id: "__root__" | "/" | "/map" | "/trips" | "/stops" | "/alerts" | "/assistant" | "/settings" | "/admin" | "/api/chat";
  fileRoutesById: FileRoutesById;
}
declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": { id: "/"; path: "/"; fullPath: "/"; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport };
    "/map": { id: "/map"; path: "/map"; fullPath: "/map"; preLoaderRoute: typeof MapRouteImport; parentRoute: typeof rootRouteImport };
    "/trips": { id: "/trips"; path: "/trips"; fullPath: "/trips"; preLoaderRoute: typeof TripsRouteImport; parentRoute: typeof rootRouteImport };
    "/stops": { id: "/stops"; path: "/stops"; fullPath: "/stops"; preLoaderRoute: typeof StopsRouteImport; parentRoute: typeof rootRouteImport };
    "/alerts": { id: "/alerts"; path: "/alerts"; fullPath: "/alerts"; preLoaderRoute: typeof AlertsRouteImport; parentRoute: typeof rootRouteImport };
    "/assistant": { id: "/assistant"; path: "/assistant"; fullPath: "/assistant"; preLoaderRoute: typeof AssistantRouteImport; parentRoute: typeof rootRouteImport };
    "/settings": { id: "/settings"; path: "/settings"; fullPath: "/settings"; preLoaderRoute: typeof SettingsRouteImport; parentRoute: typeof rootRouteImport };
    "/admin": { id: "/admin"; path: "/admin"; fullPath: "/admin"; preLoaderRoute: typeof AdminRouteImport; parentRoute: typeof rootRouteImport };
    "/api/chat": { id: "/api/chat"; path: "/api/chat"; fullPath: "/api/chat"; preLoaderRoute: typeof ApiChatRouteImport; parentRoute: typeof rootRouteImport };
  }
}
const rootRouteChildren = { IndexRoute, MapRoute, TripsRoute, StopsRoute, AlertsRoute, AssistantRoute, SettingsRoute, AdminRoute, ApiChatRoute };
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();
import type { getRouter } from "./router";
import type { startInstance } from "./start";
declare module "@tanstack/react-start" {
  interface Register { ssr: true; router: Awaited<ReturnType<typeof getRouter>>; config: Awaited<ReturnType<typeof startInstance.getOptions>>; }
}
